### PR TITLE
for GHC-8.8.2, we want the MonadFail instance for Q, not String -> Q

### PR DESCRIPTION
**Pull request by bergey**

### CODE REVIEW

**Comment by hdgarrood** [comment]
This should probably be accompanied with some version bounds changes then, I guess?

**Comment by bergey** [comment]
It currently says  `base >= 4.7 && < 5`.  That upper bound doesn't need to go up for GHC 8.8.2.

**Comment by bergey** [comment]
Oh, and I think this change is backwards-compatible; it shouldn't break on older GHC where `fail` was part of `Monad`.

**Comment by hdgarrood** [comment]
Ah right I see, I thought the quasiquoter API had changed or something. Thanks!

**Pull request merged**
