### PR TITLE
Re-export QuasiQuoter

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
It seems like I need to build-depends on template haskell to annotate my quasiquoter. Do you think it would be ok to re-export the `QuasiQuoter` type?

Thank you for the library!

**Comment by hdgarrood** [comment]
Sounds sensible to me!

**Comment by hdgarrood** [comment]
I just realised this - just for future reference, according to the PVP this ought to be `0.1.1.0` rather than `0.1.0.2`.

**Comment by hdgarrood** [comment]
Published as 0.1.1.0

**Pull request merged**
